### PR TITLE
Moved the spec section to a separate document.

### PR DESCRIPTION
**Pull request by kburger**
Moved the spec and added a link in the readme. Up next is the question what to do with the architecture section. Do we move that to an `arch.md` document? And what should remain in the `README.md`? A general introduction, or more?

### CODE REVIEW

**Comment by rajaram5** [comment]
Is Fig. 5 missing?

**Comment by rajaram5** [comment]
BTW, a generic question. Should we move the content of README. md to the wiki to have more structure like sections? Maybe having sections is a good idea

**Comment by kburger** [comment]
> Is Fig. 5 missing?

Yes, it seems to be missing. Issue #2 refers to this too. We'll need to work on this. I'll check the archived confluence page to figure out what picture is supposed to be there.

**Comment by kburger** [comment]
> BTW, a generic question. Should we move the content of README. md to the wiki to have more structure like sections? Maybe having sections is a good idea

I'd say keep the `.md` files in the repository itself, that way we can have some provenance (more elaborate compared to the wiki history) and pull requests for the documentation. To me that's a powerful tool to have.

**Comment by kburger** [comment]
I've added the missing figure. AFAIC we can leave this PR like it is, and discuss further splitting up the `README.md` content at a later point.

**Comment by kburger** [comment]
Added more visible links on top and a table of contents section to both document, as suggested by @th0mp50n.

**Pull request merged**
