### PR TITLE
Specification synchronization.

### PR DESCRIPTION
**Pull request by kburger**
A cleanup step to make sure the specification document and the reference implementation are in sync.

### CODE REVIEW

**Comment by kburger** [comment]
When cleaning up the table in c2b9e89, I saw something that I don't fully understand yet. It might be due to a formatting error, but on line [#28](https://github.com/FAIRDataTeam/FAIRDataPoint-Spec/pull/6/commits/c2b9e89e7c50b2c769fdf48678793cbb55a3b1f1#diff-958e7270f96f5407d7d980f500805b1bR28) of the spec document there is an `r3d:providedBy` predicate in the description column of the `dct:publisher` row. Is this supposed to be there?

**Comment by rajaram5** [comment]
shall we replace r3d:api by dct:references? The use definition of this predicate can be "URLs of documents related to repositories (API documents etc)"

**Comment by rajaram5** [comment]
> When cleaning up the table in [c2b9e89](https://github.com/FAIRDataTeam/FAIRDataPoint-Spec/commit/c2b9e89e7c50b2c769fdf48678793cbb55a3b1f1), I saw something that I don't fully understand yet. It might be due to a formatting error, but on line [#28](https://github.com/FAIRDataTeam/FAIRDataPoint-Spec/pull/6/commits/c2b9e89e7c50b2c769fdf48678793cbb55a3b1f1#diff-958e7270f96f5407d7d980f500805b1bR28) of the spec document there is an `r3d:providedBy` predicate in the description column of the `dct:publisher` row. Is this supposed to be there?

I think we can remove `r3d: provideBy` from the definition.  At least it will be in sync with the definition of other layers

**Comment by rajaram5** [comment]
Shall we repharse this sentence "The data record metadata aims to describe a distribution's data on the format content level." to "The data record metadata aims to provide an abstract RDF view of a dataset."

**Pull request merged**
